# Generated by Django 3.1.2 on 2021-01-27 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='برچسب')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوداگی')),
                ('phone', models.CharField(blank=True, max_length=17, verbose_name='تلفن همراه')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('image', models.CharField(blank=True, max_length=200, null=True, verbose_name='تصویر')),
                ('register_time', models.DateTimeField(blank=True, verbose_name='اخرین بازدید')),
                ('follow', models.ManyToManyField(blank=True, to='blog.User', verbose_name='دنبال کنندگان')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('text', models.CharField(max_length=2000, verbose_name='متن')),
                ('image', models.CharField(blank=True, max_length=200, null=True, verbose_name='تصویر')),
                ('video', models.CharField(blank=True, max_length=200, null=True, verbose_name='ویدئو')),
                ('show_post', models.BooleanField(default=True, verbose_name='نمایش داده شود')),
                ('post_send_time', models.DateTimeField(verbose_name='زمان ارسال پست')),
                ('accept_by_admin', models.BooleanField(default=False, verbose_name='پست تایید شده است')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='دسته بندی ها')),
                ('post_dislike', models.ManyToManyField(blank=True, related_name='post_dislike', to='blog.User', verbose_name='نپسندیدم')),
                ('post_like', models.ManyToManyField(blank=True, related_name='post_like', to='blog.User', verbose_name='پسندیدم')),
                ('tags', models.ManyToManyField(to='blog.Tag', verbose_name='برچسب ها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to='blog.user', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='متن')),
                ('accept_by_admin', models.BooleanField(default=False, verbose_name='کامنت تایید شده است')),
                ('comment_dislike', models.ManyToManyField(blank=True, related_name='comment_dislike', to='blog.User', verbose_name='نپسندیدم')),
                ('comment_like', models.ManyToManyField(blank=True, related_name='comment_like', to='blog.User', verbose_name='پسندیدم')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='blog.user', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
