# Generated by Django 3.1.2 on 2021-02-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post_rating',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='rates'),
        ),
    ]
