# Generated by Django 3.1.2 on 2021-01-27 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='شماره تلفن همراه باید به فرمت 09123456789 باشد', regex='\\b[0]{1}[9]{1}[0-9]{9}\\b')], verbose_name='تلفن همراه'),
        ),
    ]
