# Generated by Django 3.1.2 on 2021-02-03 13:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210127_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_dislike',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_dislike',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_like',
        ),
        migrations.AddField(
            model_name='user',
            name='lastseen_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='اخرین بازدید'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='ویدئو'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن همراه باید به فرمت 09123456789 باشد', regex='\\b[0]{1}[9]{1}[0-9]{9}\\b')], verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.DateField(blank=True, null=True, verbose_name='زمان ثبت نام'),
        ),
        migrations.CreateModel(
            name='Post_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tag')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='Post_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.BooleanField(verbose_name='پسندیدن؟')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
            options={
                'verbose_name': 'پسندیدن/نپسندیدن پست',
                'verbose_name_plural': 'پسندیدن/نپسندیدن پست ها',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='blog.user')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='blog.user')),
            ],
            options={
                'verbose_name': 'ارتباطات کاربران',
                'verbose_name_plural': 'ارتباط کاربران',
            },
        ),
        migrations.CreateModel(
            name='Comment_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
            options={
                'verbose_name': 'پسندیدن/نپسندیدن نظر',
                'verbose_name_plural': 'پسندیدن/نپسندیدن نظرات',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_likes',
            field=models.ManyToManyField(blank=True, related_name='comment_like', through='blog.Comment_rating', to='blog.User', verbose_name='پسندیدم'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_likes',
            field=models.ManyToManyField(blank=True, related_name='post_like', through='blog.Post_rating', to='blog.User', verbose_name='پسندیدم'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(through='blog.Post_tag', to='blog.Tag', verbose_name='برچسب ها'),
        ),
        migrations.AlterField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(blank=True, through='blog.Follow', to='blog.User', verbose_name='دنبال کنندگان'),
        ),
    ]
