# Generated by Django 3.1.2 on 2021-02-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210227_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_rating',
            name='positive',
            field=models.BooleanField(default=1, verbose_name='پسندیدن؟'),
            preserve_default=False,
        ),
    ]
