# Generated by Django 3.1.2 on 2021-02-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_rating_positive'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post_rating',
            name='rates',
        ),
        migrations.AddConstraint(
            model_name='comment_rating',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='commentrates'),
        ),
        migrations.AddConstraint(
            model_name='post_rating',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='postrates'),
        ),
    ]
