# Generated by Django 3.1.2 on 2021-02-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210203_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='supercategories',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='سر دسته'),
            preserve_default=False,
        ),
    ]
