# Generated by Django 3.1.2 on 2021-02-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210228_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='post_imgs', verbose_name='تصویر'),
            preserve_default=False,
        ),
    ]
