# Generated by Django 3.1.2 on 2021-03-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210301_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_tag',
            options={'verbose_name': 'برچسب پست', 'verbose_name_plural': 'برچسب های پست'},
        ),
    ]
