# Generated by Django 3.1.2 on 2021-03-02 11:56

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210302_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True, validators=[blog.models.User.validate_username_custom], verbose_name='نام کاربری'),
        ),
    ]
