# Generated by Django 3.1.2 on 2021-02-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210208_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='', verbose_name='تصویر'),
        ),
    ]
