# Generated by Django 3.1.2 on 2021-02-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_user_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='ابرکاربر'),
        ),
    ]
