# Generated by Django 3.1.2 on 2021-02-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210215_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('accept_comment', 'تایید کردن نظر'), ('rate_comment', 'پسندیدن/نپسندیدن نظر')], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('accept_post', 'تایید کردن پست'), ('show_post', 'نمایش دادن پست'), ('rate_post', 'پسندیدن/نپسندیدن پست')], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
    ]
